ace.define("ace/theme/chocolate",["require","exports","module","ace/lib/dom"], function(acequire, exports, module) {

exports.isDark = true;
exports.cssClass = "ace-chocolate";
exports.cssText = "/* THIS THEME WAS AUTOGENERATED BY Theme.tmpl.css (UUID: 6ea408ea-56e8-b710-aa24-0004af7580c1) */\
.ace-chocolate .ace_gutter {\
background: #e8e8e8;\
color: #333;\
}\
.ace-chocolate .ace_print-margin {\
width: 1px;\
background: #e8e8e8;\
}\
.ace-chocolate {\
background-color: #150f08;\
color: #ffffff;\
}\
.ace-chocolate .ace_cursor {\
color: #f8f8f0;\
}\
.ace-chocolate .ace_marker-layer .ace_selection {\
background: #8B6E46;\
}\
.ace-chocolate.ace_multiselect .ace_selection.ace_start {\
box-shadow: 0 0 3px 0px #150f08;\
border-radius: 2px;\
}\
.ace-chocolate .ace_marker-layer .ace_step {\
background: rgb(198, 219, 174);\
}\
.ace-chocolate .ace_marker-layer .ace_bracket {\
margin: -1px 0 0 -1px;\
border: 1px solid #3b3a32;\
}\
.ace-chocolate .ace_marker-layer .ace_active-line {\
background: #362715;\
}\
.ace-chocolate .ace_gutter-active-line {\
background-color: #362715;\
}\
.ace-chocolate .ace_marker-layer .ace_selected-word {\
border: 1px solid #8B6E46;\
}\
.ace-chocolate .ace_fold {\
background-color: #E2CDB0;\
border-color: #ffffff;\
}\
.ace-chocolate .ace_keyword{color:#B99768;}.ace-chocolate .ace_keyword.ace_other.ace_unit{color:#8B6E46;}.ace-chocolate .ace_constant.ace_language{color:#CCB697;}.ace-chocolate .ace_constant.ace_numeric{color:#F7A21B;}.ace-chocolate .ace_constant.ace_character{color:#CCB697;}.ace-chocolate .ace_constant.ace_other{color:#CCB697;}.ace-chocolate .ace_support.ace_function{color:#8B6E46;}.ace-chocolate .ace_support.ace_constant{color:#CCB697;}.ace-chocolate .ace_support.ace_constant.ace_property-value{color:#F7A21B;}.ace-chocolate .ace_support.ace_class{font-style:italic;\
color:#CCB697;}.ace-chocolate .ace_support.ace_type{font-style:italic;\
color:#CCB697;}.ace-chocolate .ace_storage{color:#CCB697;}.ace-chocolate .ace_storage.ace_type{color:#8B6E46;}.ace-chocolate .ace_invalid{color:#f8f8f0;\
background-color:#00a8c6;}.ace-chocolate .ace_invalid.ace_deprecated{color:#f8f8f0;\
background-color:#00a8c6;}.ace-chocolate .ace_string{color:#F7A21B;}.ace-chocolate .ace_comment{color:#795431;}.ace-chocolate .ace_variable{color:#E2CDB0;}.ace-chocolate .ace_variable.ace_parameter{font-style:italic;}.ace-chocolate .ace_entity.ace_other.ace_attribute-name{color:#CCB697;}.ace-chocolate .ace_entity.ace_name.ace_function{color:#E2CDB0;}.ace-chocolate .ace_entity.ace_name.ace_tag{color:#8B6E46;}";

var dom = acequire("../lib/dom");
dom.importCssString(exports.cssText, exports.cssClass);
});
